/**
 * In-browser replacement for the old `/api/*` endpoints.
 *
 * This module deliberately mirrors the logic that used to live in
 * `server/src/index.ts` — the tier floors, the retry loop, the daily seed
 * derivation — because the pre-rendered daily archive pages are generated by
 * the native build of the same engine. If the seed derivation here drifted
 * from the build script, the site would show a different "daily" puzzle than
 * its own archive page for that date.
 */

import { engine } from "./wasm";
import { dailySeed, todayUTC } from "./daily-seed";

export type Variant = "classic" | "xsudoku" | "jigsaw" | "killer";

export type TierLabel = "easy" | "medium" | "hard" | "diabolical" | "nightmare";

export type Grade =
  | {
      outcome: "solved";
      tier: number;
      tier_label: TierLabel;
      steps: number;
      technique_counts: Record<string, number>;
    }
  | { outcome: "stuck"; steps_taken: number }
  | { outcome: "error"; error: string };

/**
 * A grade attached to a puzzle we generated ourselves. The engine only returns
 * an `error` grade for malformed input, which can't happen for a puzzle it just
 * produced — `getPuzzle` throws rather than surfacing one.
 */
export type PuzzleGrade = Exclude<Grade, { outcome: "error" }>;

export interface Puzzle {
  variant: Variant;
  givens: string;
  solution: string;
  clue_count: number;
  size?: number;
  diagonals?: boolean;
  box_of?: number[];
  cages?: Array<{ cells: number[]; sum: number }>;
  grade?: PuzzleGrade;
  requested_tier?: string;
  tier_matched?: boolean;
}

export type SolveResult =
  | { outcome: "unique"; solution: string }
  | { outcome: "multiple" }
  | { outcome: "unsolvable" }
  | { outcome: "error"; error: string };

const VARIANTS: ReadonlySet<string> = new Set(["classic", "xsudoku", "jigsaw", "killer"]);

// 16×16 is exposed only for classic + xsudoku (jigsaw/killer deferred —
// perf + cage UX).
const SIZE_16_VARIANTS: ReadonlySet<string> = new Set(["classic", "xsudoku"]);

export function variantSupportsSize(variant: string, size: number): boolean {
  if (size === 16) return SIZE_16_VARIANTS.has(variant);
  return size === 6 || size === 9;
}

// Per-(variant,tier) clue floor at 9×9, from the engine sweep (2026-06-04).
// Carried over verbatim from the server so difficulty distribution is
// unchanged by the migration.
const TIER_FLOORS: Record<string, Record<string, number>> = {
  classic: { easy: 32, medium: 28, nightmare: 22 },
  xsudoku: { easy: 32, medium: 26, nightmare: 24 },
  jigsaw: { easy: 32, medium: 28, nightmare: 26 },
};

function tierFloorFor(variant: string, size: number, tier: string): number | undefined {
  if (size !== 9) return undefined;
  return TIER_FLOORS[variant]?.[tier];
}

/** Engine default when no floor applies (matches the CLI's `--min-clues` default). */
const DEFAULT_MIN_CLUES = 28;

/** Seeds are passed to a u64 on the Rust side; stay inside the safe range. */
function randomSeed(): number {
  return Math.floor(Math.random() * Number.MAX_SAFE_INTEGER);
}

function gradeInputFor(p: Puzzle): string {
  // Classic can go over as a bare string; the variants need the JSON form so
  // the engine can rebuild the diagonal/box/cage constraints.
  if (p.variant === "classic") return p.givens;
  return JSON.stringify({
    givens: p.givens,
    variant: p.variant,
    ...(p.box_of ? { box_of: p.box_of } : {}),
    ...(p.cages ? { cages: p.cages } : {}),
  });
}

/**
 * 16×16 puzzles take ~16 seconds to generate even in native code, which is why
 * the old server only just managed them inside its 15s timeout. They come from
 * a pre-generated pool shipped as a static asset instead.
 */
let poolCache: Promise<Record<string, Puzzle[]>> | null = null;

function pool(): Promise<Record<string, Puzzle[]>> {
  poolCache ??= fetch("/pool-16.json")
    .then((r) => {
      if (!r.ok) throw new Error(`16×16 pool unavailable (${r.status})`);
      return r.json() as Promise<Record<string, Puzzle[]>>;
    })
    .catch((e: unknown) => {
      poolCache = null;
      throw e;
    });
  return poolCache;
}

async function from16Pool(variant: string, tier: string | null): Promise<Puzzle> {
  const all = await pool();
  const choices = all[variant] ?? [];
  if (choices.length === 0) throw new Error(`no 16×16 puzzles available for ${variant}`);
  // Honour the requested tier when the pool actually contains one, otherwise
  // fall back to the whole set — same "best effort" contract the server had.
  const matching = tier
    ? choices.filter((p) => p.grade?.outcome === "solved" && p.grade.tier_label === tier)
    : choices;
  const from = matching.length > 0 ? matching : choices;
  const pick = from[Math.floor(Math.random() * from.length)]!;
  return {
    ...pick,
    size: 16,
    ...(tier && matching.length === 0
      ? { requested_tier: tier, tier_matched: false }
      : {}),
  };
}

/** Replaces `GET /api/puzzle`. */
export async function getPuzzle(opts: {
  variant: string;
  size: number;
  tier?: string | null;
  seed?: number;
}): Promise<Puzzle> {
  const { variant, size } = opts;
  const tier = opts.tier ?? null;

  if (!VARIANTS.has(variant)) throw new Error(`unknown variant: ${variant}`);
  if (![6, 9, 16].includes(size)) throw new Error(`unsupported size: ${size}`);
  if (!variantSupportsSize(variant, size)) {
    throw new Error(`${variant} is not available at ${size}×${size}`);
  }

  if (size === 16) return from16Pool(variant, tier);

  const eng = await engine();
  const minClues = tier ? (tierFloorFor(variant, size, tier) ?? DEFAULT_MIN_CLUES) : DEFAULT_MIN_CLUES;

  // Same shape as the server's loop: keep generating until the graded tier
  // matches what was asked for, then give up gracefully.
  const maxRetries = tier ? 60 : 1;
  let last: Puzzle | null = null;
  let lastGrade: PuzzleGrade | null = null;
  let matched = !tier;

  for (let i = 0; i < maxRetries; i++) {
    const seed = opts.seed !== undefined ? opts.seed + i : randomSeed();
    const puzzle = eng.generate(variant, size, minClues, seed) as Puzzle;
    if ((puzzle as unknown as { outcome?: string }).outcome === "error") {
      throw new Error((puzzle as unknown as { error: string }).error);
    }
    last = puzzle;
    const graded = eng.grade(gradeInputFor(puzzle)) as Grade;
    if (graded.outcome === "error") throw new Error(graded.error);
    lastGrade = graded;
    if (tier && lastGrade.outcome === "solved" && lastGrade.tier_label === tier) {
      matched = true;
      break;
    }
    if (!tier) break;
  }

  if (!last) throw new Error("generator produced nothing");

  const body: Puzzle = { ...last, size };
  if (lastGrade) body.grade = lastGrade;
  if (tier && !matched) {
    body.requested_tier = tier;
    body.tier_matched = false;
  }
  return body;
}

/** Replaces `POST /api/solve`. */
export async function solvePuzzle(puzzle: string): Promise<SolveResult> {
  const eng = await engine();
  return eng.solve(puzzle) as SolveResult;
}

/** Replaces `POST /api/grade`. */
export async function gradePuzzle(puzzle: string, variant: string = "classic"): Promise<Grade> {
  const eng = await engine();
  const input = variant === "classic" ? puzzle : JSON.stringify({ givens: puzzle, variant });
  return eng.grade(input) as Grade;
}

// --- daily ----------------------------------------------------------------

export interface DailyData {
  date: string;
  classic: Puzzle;
  killer: Puzzle;
}

// The seed derivation is shared with the build-time prerenderer so the daily
// puzzle in the app and the one on its archive page cannot diverge.
export { dailySeed, todayUTC } from "./daily-seed";

function gradeOrThrow(g: Grade): PuzzleGrade {
  if (g.outcome === "error") throw new Error(g.error);
  return g;
}

const dailyCache = new Map<string, Promise<DailyData>>();

/** Replaces `GET /api/daily`. */
export function getDaily(date: string = todayUTC()): Promise<DailyData> {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    return Promise.reject(new Error("date must be YYYY-MM-DD"));
  }
  let entry = dailyCache.get(date);
  if (!entry) {
    entry = (async () => {
      const eng = await engine();
      const classic = eng.generate("classic", 9, 28, dailySeed(date, "classic")) as Puzzle;
      const killer = eng.generate("killer", 9, 28, dailySeed(date, "killer")) as Puzzle;
      classic.grade = gradeOrThrow(eng.grade(gradeInputFor(classic)) as Grade);
      killer.grade = gradeOrThrow(eng.grade(gradeInputFor(killer)) as Grade);
      return { date, classic, killer };
    })();
    entry.catch(() => dailyCache.delete(date));
    dailyCache.set(date, entry);
  }
  return entry;
}
