import { describe, it, expect } from "vitest";
import raw from "./cage-combos.json?raw";
import { combinations, mustAppear, sumRange } from "./combos";

// Engine-generated ground truth — regenerated by the Rust test
// `regenerate_calculator_fixture`, pinned to `cage_can_fill` semantics by
// `calculator_fixture_matches_engine` (engine/src/techniques.rs).
interface FullEntry {
  n: number;
  cells: number;
  sum: number;
  combos: number[][];
}
interface Count16 {
  cells: number;
  sum: number;
  count: number;
}
const FIXTURE = JSON.parse(raw) as { full: FullEntry[]; counts16: Count16[] };

describe("combinations vs engine fixture", () => {
  it("matches every full 6×6 and 9×9 entry (and 16×16 spot lists) exactly", () => {
    for (const e of FIXTURE.full) {
      expect(combinations({ n: e.n, cells: e.cells, sum: e.sum }), `n=${e.n} cells=${e.cells} sum=${e.sum}`).toEqual(
        e.combos,
      );
    }
  });

  it("matches every 16×16 per-(cells,sum) count", () => {
    for (const e of FIXTURE.counts16) {
      expect(combinations({ n: 16, cells: e.cells, sum: e.sum }).length, `cells=${e.cells} sum=${e.sum}`).toBe(
        e.count,
      );
    }
  });

  it("totals match the counts the page cites: 502 at 9×9, 57 at 6×6", () => {
    const total = (n: number) =>
      FIXTURE.full.filter((e) => e.n === n).reduce((acc, e) => acc + e.combos.length, 0);
    expect(total(9)).toBe(502);
    expect(total(6)).toBe(57);
  });
});

describe("include/exclude filters", () => {
  it("include keeps only combinations containing every required digit", () => {
    expect(combinations({ n: 9, cells: 2, sum: 10, include: [9] })).toEqual([[1, 9]]);
    expect(combinations({ n: 9, cells: 3, sum: 15, include: [1, 5] })).toEqual([[1, 5, 9]]);
  });

  it("exclude drops combinations containing any barred digit", () => {
    expect(combinations({ n: 9, cells: 2, sum: 10, exclude: [1] })).toEqual([
      [2, 8],
      [3, 7],
      [4, 6],
    ]);
  });

  it("include and exclude compose", () => {
    expect(combinations({ n: 9, cells: 3, sum: 12, include: [2], exclude: [1] })).toEqual([
      [2, 3, 7],
      [2, 4, 6],
    ]);
  });

  it("contradictory filters yield no combinations", () => {
    expect(combinations({ n: 9, cells: 2, sum: 10, include: [5], exclude: [5] })).toEqual([]);
  });
});

describe("mustAppear", () => {
  it("finds digits present in every combination", () => {
    expect(mustAppear(combinations({ n: 9, cells: 2, sum: 17 }))).toEqual([8, 9]);
    expect(mustAppear(combinations({ n: 9, cells: 4, sum: 30 }))).toEqual([6, 7, 8, 9]);
  });

  it("returns nothing when no digit is shared or there are no combinations", () => {
    expect(mustAppear(combinations({ n: 9, cells: 2, sum: 10 }))).toEqual([]);
    expect(mustAppear([])).toEqual([]);
  });
});

describe("sumRange", () => {
  it("gives the reachable sum bounds", () => {
    expect(sumRange(9, 2)).toEqual({ min: 3, max: 17 });
    expect(sumRange(9, 9)).toEqual({ min: 45, max: 45 });
    expect(sumRange(6, 6)).toEqual({ min: 21, max: 21 });
    expect(sumRange(16, 16)).toEqual({ min: 136, max: 136 });
  });

  it("out-of-range sums have no combinations", () => {
    expect(combinations({ n: 9, cells: 2, sum: 2 })).toEqual([]);
    expect(combinations({ n: 9, cells: 2, sum: 18 })).toEqual([]);
  });
});
